### ISSUE TITLE
TypeError: Cannot read property 'navigationStart' of undefined

### ISSUE THREAD

**Issue by JeromeLin** [ustbhuangyi/better-scroll#773]
从1.14.1升级1.15.0/1.15.1在jest下报错。

TypeError: Cannot read property 'navigationStart' of undefined

      at getNow (node_modules/better-scroll/dist/bscroll.js:150:110)
      at BScroll._animate (node_modules/better-scroll/dist/bscroll.js:1490:21)
      at BScroll.scrollTo (node_modules/better-scroll/dist/bscroll.js:1587:12)
      at BScroll.resetPosition (node_modules/better-scroll/dist/bscroll.js:1649:10)
      at BScroll.scrollTo (node_modules/better-scroll/dist/bscroll.js:1575:19)
      at BScroll._init (node_modules/better-scroll/dist/bscroll.js:548:12)
      at new BScroll (node_modules/better-scroll/dist/bscroll.js:3450:8)
      at Wheel.componentDidMount (components/wheel/Wheel.tsx:2374:20)
      at commitLifeCycles (node_modules/react-dom/cjs/react-dom.development.js:14362:22)
      at commitAllLifeCycles (node_modules/react-dom/cjs/react-dom.development.js:15463:7)
      at HTMLUnknownElement.callCallback (node_modules/react-dom/cjs/react-dom.development.js:100:14)
      at invokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:193:27)
      at HTMLUnknownElementImpl._dispatch (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:119:9)
      at HTMLUnknownElementImpl.dispatchEvent (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:82:17)
      at HTMLUnknownElementImpl.dispatchEvent (node_modules/jsdom/lib/jsdom/living/nodes/HTMLElement-impl.js:30:27)
      at HTMLUnknownElement.dispatchEvent (node_modules/jsdom/lib/jsdom/living/generated/EventTarget.js:157:21)
      at Object.invokeGuardedCallbackDev (node_modules/react-dom/cjs/react-dom.development.js:138:16)
      at invokeGuardedCallback (node_modules/react-dom/cjs/react-dom.development.js:187:29)
      at commitRoot (node_modules/react-dom/cjs/react-dom.development.js:15604:7)
      at completeRoot (node_modules/react-dom/cjs/react-dom.development.js:16619:34)
      at performWorkOnRoot (node_modules/react-dom/cjs/react-dom.development.js:16564:9)
      at performWork (node_modules/react-dom/cjs/react-dom.development.js:16483:7)
      at performSyncWork (node_modules/react-dom/cjs/react-dom.development.js:16455:3)
      at requestWork (node_modules/react-dom/cjs/react-dom.development.js:16355:5)
      at scheduleWork$1 (node_modules/react-dom/cjs/react-dom.development.js:16219:11)
      at scheduleRootUpdate (node_modules/react-dom/cjs/react-dom.development.js:16786:3)
      at updateContainerAtExpirationTime (node_modules/react-dom/cjs/react-dom.development.js:16813:10)
      at updateContainer (node_modules/react-dom/cjs/react-dom.development.js:16840:10)
      at ReactRoot.Object.<anonymous>.ReactRoot.render (node_modules/react-dom/cjs/react-dom.development.js:17123:3)
      at node_modules/react-dom/cjs/react-dom.development.js:17263:14
      at unbatchedUpdates (node_modules/react-dom/cjs/react-dom.development.js:16680:10)
      at legacyRenderSubtreeIntoContainer (node_modules/react-dom/cjs/react-dom.development.js:17259:5)
      at Object.render (node_modules/react-dom/cjs/react-dom.development.js:17318:12)
      at Object.render (node_modules/enzyme-adapter-react-16/build/ReactSixteenAdapter.js:352:114)
      at new ReactWrapper (node_modules/enzyme/build/ReactWrapper.js:134:16)
      at mount (node_modules/enzyme/build/mount.js:21:10)
      at Object.<anonymous> (components/wheel/__tests__/index.test.jsx:8:21)

**Comment by theniceangel** [comment]
jest用的是 jsdom。劫持下 window.performance.timing，自己 mock 试试。
